[package]
name = "rust-db-writer"
version = "0.1.0"
authors = ["Salvador Guzman <guzmansalv@gmail.com>"]
edition = "2018"

[[bin]]
name = "db-writer"
path = "src/main.rs"

[dependencies]
actix = "0.8.2"
actix-protobuf = "0.4.0"
actix-web = "1.0.0"
bytes = "0.4.12"
chrono = "0.4.6"
env_logger = "0.6.1"
postgres = { version = "0.15.2", features = ["with-chrono"] }
prost = "0.5"
prost-derive = "0.5"
